# Generated by Django 5.0.2 on 2024-03-02 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 18, 2, 1, 355270), help_text='date joined'),
        ),
    ]
