# Generated by Django 5.0.2 on 2024-03-04 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_rename_user_name_myuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 18, 23, 4, 345914), help_text='date joined'),
        ),
    ]
